# Generated by Django 4.1.7 on 2023-03-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeassagingApp', '0004_remove_message_user_message_reciever_message_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='message',
            name='is_seen',
            field=models.BooleanField(null=True),
        ),
    ]
