# Generated by Django 4.1.7 on 2023-03-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeassagingApp', '0005_alter_message_options_message_is_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_seen',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
